//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ukUA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ukUA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Properties.Resources.ukUA", typeof(Resources_ukUA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Застосувати.
        /// </summary>
        internal static string apply_btn {
            get {
                return ResourceManager.GetString("apply_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обчислити.
        /// </summary>
        internal static string calculate_text_btn {
            get {
                return ResourceManager.GetString("calculate_text_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        internal static string cancel_btn {
            get {
                return ResourceManager.GetString("cancel_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштувати алгоритм.
        /// </summary>
        internal static string configure_algorithm {
            get {
                return ResourceManager.GetString("configure_algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштувати карту .
        /// </summary>
        internal static string configure_map {
            get {
                return ResourceManager.GetString("configure_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ця програма вирішує задачу комівояжера, використовуючи різні алгоритми оптимізації. Вона аналізує маршрути між містами та знаходить найефективніший шлях для мінімізації загальної подорожі, демонструючи можливості різних методів..
        /// </summary>
        internal static string description_text {
            get {
                return ResourceManager.GetString("description_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрати алгоритм:.
        /// </summary>
        internal static string select_algorithm {
            get {
                return ResourceManager.GetString("select_algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати графік.
        /// </summary>
        internal static string show_chart {
            get {
                return ResourceManager.GetString("show_chart", resourceCulture);
            }
        }
    }
}
